import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onErrorContainer,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(25.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 16.fSize,
          fontFamily: 'Helvetica',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: 14.fSize,
          fontFamily: 'Helvetica',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray500,
          fontSize: 12.fSize,
          fontFamily: 'Helvetica',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: colorScheme.primaryContainer,
          fontSize: 12.fSize,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: appTheme.black900,
          fontSize: 16.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray500,
          fontSize: 14.fSize,
          fontFamily: 'Helvetica',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF001D9A),
    primaryContainer: Color(0XFF6F6F6F),
    secondary: Color(0XFF6F6F6F),
    secondaryContainer: Color(0XFF001D9A),
    tertiary: Color(0XFF6F6F6F),
    tertiaryContainer: Color(0XFF001D9A),

    // Background colors
    background: Color(0XFF6F6F6F),

    // Surface colors
    surface: Color(0XFF6F6F6F),
    surfaceTint: Color(0XFF98AAF7),
    surfaceVariant: Color(0XFF001D9A),

    // Error colors
    error: Color(0XFF98AAF7),
    errorContainer: Color(0XFF3F3F3F),
    onError: Color(0XFF001D9A),
    onErrorContainer: Color(0XFFFFFFFF),

    // On colors(text colors)
    onBackground: Color(0XFF0001CB),
    onInverseSurface: Color(0XFF001D9A),
    onPrimary: Color(0XFF98AAF7),
    onPrimaryContainer: Color(0XFF0001CB),
    onSecondary: Color(0XFF0001CB),
    onSecondaryContainer: Color(0XFF98AAF7),
    onTertiary: Color(0XFF0001CB),
    onTertiaryContainer: Color(0XFF98AAF7),

    // Other colors
    outline: Color(0XFF98AAF7),
    outlineVariant: Color(0XFF6F6F6F),
    scrim: Color(0XFF6F6F6F),
    shadow: Color(0XFF98AAF7),

    // Inverse colors
    inversePrimary: Color(0XFF6F6F6F),
    inverseSurface: Color(0XFF98AAF7),

    // Pending colors
    onSurface: Color(0XFF0001CB),
    onSurfaceVariant: Color(0XFF98AAF7),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blue100 => Color(0XFFCED7FB);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray400 => Color(0XFF888888);

  // Gray
  Color get gray100 => Color(0XFFF0F2F5);
  Color get gray200 => Color(0XFFEBEBEB);
  Color get gray300 => Color(0XFFDDDDDD);
  Color get gray500 => Color(0XFF9D9D9D);
  Color get gray700 => Color(0XFF65676B);
  Color get gray70001 => Color(0XFF5F5F5F);

  // Indigo
  Color get indigo500 => Color(0XFF415CD1);
  Color get indigoA100 => Color(0XFF899DF5);
  Color get indigoA400 => Color(0XFF4464F1);

  // Yellow
  Color get yellowA200 => Color(0XFFFEFE00);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
